/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author salon
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmMesa = new javax.swing.JMenu();
        jmMesero = new javax.swing.JMenu();
        jmPedido = new javax.swing.JMenu();
        jmReserva = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jmiMesero = new javax.swing.JMenuItem();
        jAMesa = new javax.swing.JMenuItem();
        jmiProducto = new javax.swing.JMenuItem();
        jmiContable = new javax.swing.JMenuItem();
        jmiStock = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdPrincipalLayout = new javax.swing.GroupLayout(jdPrincipal);
        jdPrincipal.setLayout(jdPrincipalLayout);
        jdPrincipalLayout.setHorizontalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1009, Short.MAX_VALUE)
        );
        jdPrincipalLayout.setVerticalGroup(
            jdPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jmMesa.setText("Mesas");
        jmMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMesaMouseClicked(evt);
            }
        });
        jmMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMesaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmMesa);

        jmMesero.setText("Meseros");
        jMenuBar1.add(jmMesero);

        jmPedido.setText("Pedidos");
        jmPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPedidoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmPedido);

        jmReserva.setText("Reserva");
        jMenuBar1.add(jmReserva);

        jMenu6.setText("Administracion");

        jmiMesero.setText("Contratar mesero");
        jmiMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMeseroActionPerformed(evt);
            }
        });
        jMenu6.add(jmiMesero);

<<<<<<< Updated upstream
        jMenuItem2.setText("Añadir mesa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);
=======
        jAMesa.setText("Añadir mesa");
        jAMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAMesaActionPerformed(evt);
            }
        });
        jMenu6.add(jAMesa);
>>>>>>> Stashed changes

        jmiProducto.setText("Cargar producto");
        jmiProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductoActionPerformed(evt);
            }
        });
        jMenu6.add(jmiProducto);

        jmiContable.setText("Contable");
        jmiContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContableActionPerformed(evt);
            }
        });
        jMenu6.add(jmiContable);

        jmiStock.setText("Stock productos");
        jmiStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStockActionPerformed(evt);
            }
        });
        jMenu6.add(jmiStock);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMesaMouseClicked
        // TODO add your handling code here:
        jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewSalonMesa interMesa = new ViewSalonMesa();
        interMesa.setVisible(true);
        jdPrincipal.add(interMesa);
        jdPrincipal.moveToFront(interMesa);
    }//GEN-LAST:event_jmMesaMouseClicked

    private void jmiMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMeseroActionPerformed
        // TODO add your handling code here:
        jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewMeseroAdmin interMeseroAdmin = new ViewMeseroAdmin();
        interMeseroAdmin.setVisible(true);
        jdPrincipal.add(interMeseroAdmin);
        jdPrincipal.moveToFront(interMeseroAdmin);
    }//GEN-LAST:event_jmiMeseroActionPerformed

    private void jmiProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductoActionPerformed
        // TODO add your handling code here:
        jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewProductoAdmin interProductoAdmin = new ViewProductoAdmin();
        interProductoAdmin.setVisible(true);
        jdPrincipal.add(interProductoAdmin);
        jdPrincipal.moveToFront(interProductoAdmin);
    }//GEN-LAST:event_jmiProductoActionPerformed

    private void jmPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPedidoMouseClicked
        // TODO add your handling code here:
        jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewPedido interPedido = new ViewPedido();
        interPedido.setVisible(true);
        jdPrincipal.add(interPedido);
        jdPrincipal.moveToFront(interPedido);
    }//GEN-LAST:event_jmPedidoMouseClicked

    private void jmiContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContableActionPerformed
        // TODO add your handling code here:
          jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewPedidoAdmin interPedidoAdmin = new ViewPedidoAdmin();
        interPedidoAdmin.setVisible(true);
        jdPrincipal.add(interPedidoAdmin);
        jdPrincipal.moveToFront(interPedidoAdmin);
    }//GEN-LAST:event_jmiContableActionPerformed

    private void jmiStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStockActionPerformed
        
        jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewStockProductos interStock = new ViewStockProductos();
        interStock.setVisible(true);
        jdPrincipal.add(interStock);
        jdPrincipal.moveToFront(interStock);
        
    }//GEN-LAST:event_jmiStockActionPerformed


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jmMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMesaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmMesaActionPerformed

    private void jAMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAMesaActionPerformed
    
     jdPrincipal.removeAll();
        jdPrincipal.repaint();
        ViewMesaAdmin interMesaAdmin = new ViewMesaAdmin();
        interMesaAdmin.setVisible(true);
        jdPrincipal.add(interMesaAdmin);
        jdPrincipal.moveToFront(interMesaAdmin);
        
    }//GEN-LAST:event_jAMesaActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAMesa;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdPrincipal;
    private javax.swing.JMenu jmMesa;
    private javax.swing.JMenu jmMesero;
    private javax.swing.JMenu jmPedido;
    private javax.swing.JMenu jmReserva;
    private javax.swing.JMenuItem jmiContable;
    private javax.swing.JMenuItem jmiMesero;
    private javax.swing.JMenuItem jmiProducto;
    private javax.swing.JMenuItem jmiStock;
    // End of variables declaration//GEN-END:variables
}
