/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import Entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author salon
 */
public class ViewListarReservas extends javax.swing.JInternalFrame {
            private ReservaData reservaData;
            private Reserva reserva;
    
         private DefaultTableModel modeloTabla = new DefaultTableModel(){
         
          @Override
          public boolean isCellEditable(int fila, int columna) {
              
              return false;
          }
     };
    /**
     * Creates new form ViewListarReservas
     */
    public ViewListarReservas() {
        reservaData = new ReservaData();
        reserva = new Reserva();
        initComponents();
        armarCabecera();
        cargarCombo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReservas = new javax.swing.JTable();
        jcbReservaId = new javax.swing.JComboBox<>();
        jcbMesaId = new javax.swing.JComboBox<>();
        jrbOrdenar = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbTodas = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();

        jtReservas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtReservas);

        jcbReservaId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbReservaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbReservaIdActionPerformed(evt);
            }
        });

        jcbMesaId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jrbOrdenar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jrbOrdenar.setText("Ordenar fecha");
        jrbOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOrdenarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Lista de reservas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Id reserva:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Id mesa:");

        jbEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbEliminar.setText("Eliminar");

        jbSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbTodas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbTodas.setText("Mostrar todas");
        jbTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTodasActionPerformed(evt);
            }
        });

        jbModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbModificar.setText("Modificar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jbSalir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jcbMesaId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcbReservaId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 20, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbTodas)
                                            .addComponent(jrbOrdenar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbReservaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbMesaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addComponent(jrbOrdenar)
                        .addGap(18, 18, 18)
                        .addComponent(jbTodas)
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminar)
                    .addComponent(jbSalir)
                    .addComponent(jbModificar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcbReservaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbReservaIdActionPerformed
        // TODO add your handling code here:
         borrarFilaTabla();
         cargarDatos();
    }//GEN-LAST:event_jcbReservaIdActionPerformed

    private void jbTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTodasActionPerformed
        // TODO add your handling code here:
         tablaCompleta();
    }//GEN-LAST:event_jbTodasActionPerformed

    private void jrbOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOrdenarActionPerformed
        // TODO add your handling code here:
        tablaCompletaOrdenada();
        
    }//GEN-LAST:event_jrbOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbTodas;
    private javax.swing.JComboBox<String> jcbMesaId;
    private javax.swing.JComboBox<Reserva> jcbReservaId;
    private javax.swing.JRadioButton jrbOrdenar;
    private javax.swing.JTable jtReservas;
    // End of variables declaration//GEN-END:variables
       private void armarCabecera(){ 
        this.modeloTabla.addColumn("ID");
        this.modeloTabla.addColumn("DNI");
        this.modeloTabla.addColumn("Nombre");
        this.modeloTabla.addColumn("Fecha");
        this.modeloTabla.addColumn("Numero de mesa");
        jtReservas.setModel(modeloTabla);
    } 
    
  public void cargarCombo() {
    ArrayList<Reserva> reservas = (ArrayList<Reserva>) reservaData.obtenerReservas();
    jcbReservaId.removeAllItems();
    for (Reserva r : reservas) {
        jcbReservaId.addItem(r);
    }
}  
       
    public void tablaCompleta(){
        borrarFilaTabla();
         ArrayList<Reserva> reservas= (ArrayList<Reserva>) reservaData.obtenerReservas();
        for(Reserva r:reservas){
            modeloTabla.addRow(new Object[]{r.getId_reserva(),r.getDni_cliente(), r.getNombre_cliente(), r.getFecha_reserva(), r.getMesa().getNumero()});
        }
        
    } 
    public void tablaCompletaOrdenada(){
        borrarFilaTabla();
         ArrayList<Reserva> reservas= (ArrayList<Reserva>) reservaData.obtenerReservasOrden();
        for(Reserva r:reservas){
            modeloTabla.addRow(new Object[]{r.getId_reserva(),r.getDni_cliente(), r.getNombre_cliente(), r.getFecha_reserva(), r.getMesa().getNumero()});
        }
    }
       
   public void cargarDatos(){
    borrarFilaTabla(); 
    Reserva reservaSelec = (Reserva) jcbReservaId.getSelectedItem();
    if (reservaSelec != null) {
        int id = reservaSelec.getId_reserva();
        ArrayList<Reserva> reservas = (ArrayList<Reserva>) reservaData.obtenerReservasPorId(id);
        for(Reserva r:reservas){
           modeloTabla.addRow(new Object[]{r.getId_reserva(),r.getDni_cliente(), r.getNombre_cliente(), r.getFecha_reserva(), r.getMesa().getNumero()});
        }
    }
}
     private void borrarFilaTabla(){
        int indice=modeloTabla.getRowCount()-1;
        for(int i=indice;i>=0;i--){
            modeloTabla.removeRow(i);
        }
        
    }
}
